const EXCEL_URL='data/budget-data.json';
const REMAINING_KEY='household-budget-remaining-v2';
let excel=null;
const savedRemaining=JSON.parse(localStorage.getItem(REMAINING_KEY)||'{}');
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function saveRemaining(){localStorage.setItem(REMAINING_KEY,JSON.stringify(savedRemaining));}
function monthLabel(m){const [y,mo]=m.split('-');return `${y}年${Number(mo)}月`;}
function parseEnd(s){if(!s)return null;const m=String(s).match(/[～~]\s*(\d{4})\s*\/(\d+)/);return m?`${m[1]}-${String(Number(m[2])).padStart(2,'0')}`:null;}
function splitItems(){return (excel.splitItems||[]).map((p,i)=>{const k=`${p.name}|${p.type}|${p.row}`;return {...p,id:i+1,current:savedRemaining[k]!==undefined?savedRemaining[k]:p.remainingAmount,k};});}
function activeSplitItems(){return splitItems().filter(p=>p.current==null||Number(p.current)>0);}
function renderSummary(){const items=activeSplitItems();const known=items.reduce((s,p)=>s+(Number(p.current)||0),0);const latest=(excel.months||[]).at(-1);const plan=(excel.months||[]).slice(-1)[0]?.payments||[];const latestTotal=plan.reduce((s,p)=>s+(Number(p.amount)||0),0);document.querySelector('#summary').innerHTML=[['分割・リボ残金',known?yen(known):'未入力あり'],['直近月の分割・リボ',yen(latestTotal)],['管理中の項目',`${items.length}件`],['最新データ',excel.source||'—']].map(([l,v])=>`<div class="card"><div class="label">${l}</div><div class="value">${v}</div></div>`).join('');}
function renderSplitItems(){document.querySelector('#splitItems').innerHTML=activeSplitItems().map(p=>{const end=parseEnd(p.end);return `<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.type)}</td><td>${yen(p.monthly)}</td><td>${p.remainingAmount==null?'未入力':yen(p.remainingAmount)}</td><td><input class="input remaining-input" data-key="${esc(p.k)}" type="number" min="0" step="1" value="${p.current==null?'':p.current}" placeholder="残金を入力"></td><td>${end?monthLabel(end):'未設定'}</td></tr>`;}).join('')||'<tr><td colspan="6">表示対象の分割・リボはありません。</td></tr>';
document.querySelectorAll('.remaining-input').forEach(el=>el.addEventListener('change',()=>{savedRemaining[el.dataset.key]=Math.max(0,Number(el.value)||0);saveRemaining();render();}));}
function renderSchedules(){const targets=[...(excel.cardSchedules||[]),...(excel.serviceSchedules||[])];document.querySelector('#schedules').innerHTML=targets.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x['引落']||'記載なし')}</td><td>${esc(x['締め日']||'記載なし')}</td></tr>`).join('');}
function renderMonthlyPlan(){const items=activeSplitItems();const rows=(excel.months||[]).map(m=>{const payments=m.payments||[];const split=payments.filter(p=>p.type==='分割').reduce((s,p)=>s+(Number(p.amount)||0),0);const ribo=payments.filter(p=>p.type==='リボ').reduce((s,p)=>s+(Number(p.amount)||0),0);return {month:m.month,split,ribo,total:split+ribo};});
 document.querySelector('#monthlyPlan').innerHTML=rows.map(r=>`<tr><td><strong>${monthLabel(r.month)}</strong></td><td>${yen(r.split)}</td><td>${yen(r.ribo)}</td><td><strong>${yen(r.total)}</strong></td></tr>`).join('');}
function renderLife(){const rows=excel.lifeCostMonths||[];const sel=document.querySelector('#lifeMonth');const old=sel.value;sel.innerHTML=rows.map(r=>`<option value="${r.month}">${monthLabel(r.month)}</option>`).join('');sel.value=rows.some(r=>r.month===old)?old:(rows.at(-1)?.month||'');drawPie();sel.onchange=drawPie;}
function drawPie(){const row=(excel.lifeCostMonths||[]).find(r=>r.month===document.querySelector('#lifeMonth').value)||(excel.lifeCostMonths||[]).at(-1);if(!row)return;const entries=[['家賃',row['家賃']],['ガス',row['ガス']],['電気',row['電気']],['携帯',row['携帯']],['水道',row['水道']]].filter(x=>Number(x[1])>0);const total=entries.reduce((s,x)=>s+Number(x[1]),0);const pie=document.querySelector('#pie');pie.style.background=total?`conic-gradient(${entries.map((x,i)=>{const start=entries.slice(0,i).reduce((s,y)=>s+Number(y[1]),0)/total*360;const end=entries.slice(0,i+1).reduce((s,y)=>s+Number(y[1]),0)/total*360;const cls=['#52606d','#7b8794','#9aa5b1','#c1c8d0','#e2e5e9'][i];return `${cls} ${start}deg ${end}deg`;}).join(',')})`:'none';document.querySelector('#pieLegend').innerHTML=entries.length?entries.map(x=>`<div><span class="dot"></span>${x[0]}：${yen(x[1])}（${Math.round(Number(x[1])/total*100)}%）</div>`).join(''):'この月の生活費データはありません。';}
function render(){if(!excel)return;renderSummary();renderSplitItems();renderSchedules();renderMonthlyPlan();renderLife();document.querySelector('#dataStatus').textContent=`Excelデータ読み込み済み：${excel.source}（${(excel.months||[]).length}か月）`;}
async function loadExcel(){try{const r=await fetch(EXCEL_URL,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);excel=await r.json();render();}catch(e){console.error(e);document.querySelector('#dataStatus').textContent='Excelデータの読み込みに失敗しました。';}}
loadExcel();
