const EXCEL_URL='data/kakei.json';
const REMAINING_KEY='household-budget-remaining-v2';
const ENTRY_KEY='household-budget-entries-v1';
let excel=null;
const savedRemaining=JSON.parse(localStorage.getItem(REMAINING_KEY)||'{}');
let manualEntries=JSON.parse(localStorage.getItem(ENTRY_KEY)||'[]');
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function saveRemaining(){localStorage.setItem(REMAINING_KEY,JSON.stringify(savedRemaining));}
function saveEntries(){localStorage.setItem(ENTRY_KEY,JSON.stringify(manualEntries));}
function monthLabel(m){const [y,mo]=m.split('-');return `${y}年${Number(mo)}月`;}
function parseEnd(s){if(!s)return null;const m=String(s).match(/[～~]\s*(\d{4})\s*\/(\d+)/);return m?`${m[1]}-${String(Number(m[2])).padStart(2,'0')}`:null;}
function addMonths(month,n){const [y,m]=month.split('-').map(Number);const d=new Date(y,m-1+n,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function monthRange(start,end){const out=[];for(let m=start;m<=end;m=addMonths(m,1))out.push(m);return out;}
function splitItems(){return (excel.splitItems||[]).map((p,i)=>{const k=`${p.name}|${p.type}|${p.row}`;return {...p,id:i+1,current:savedRemaining[k]!==undefined?savedRemaining[k]:p.remainingAmount,k};});}
function activeSplitItems(){return splitItems().filter(p=>p.current==null||Number(p.current)>0);}
function manualTotals(month){return manualEntries.filter(e=>e.date.startsWith(month)).reduce((a,e)=>{a[e.kind]+=(Number(e.amount)||0);return a;},{収入:0,支出:0});}
function renderMonthlySummary(){const months=excel.months||[];const sel=document.querySelector('#summaryMonth');const old=sel.value;sel.innerHTML=months.map(m=>`<option value="${m.month}">${monthLabel(m.month)}</option>`).join('');const current=new Date().toISOString().slice(0,7);sel.value=months.some(m=>m.month===old)?old:(months.some(m=>m.month===current)?current:(months.at(-1)?.month||''));const m=months.find(x=>x.month===sel.value)||months.at(-1);if(!m)return;const extra=manualTotals(m.month);const income=Number(m.income)||0;const expense=(Number(m.expenseTotal)||0)+extra.支出;const totalIncome=income+extra.収入;const balance=totalIncome-expense;document.querySelector('#monthlySummary').innerHTML=`<div class="money-box income"><div class="money-label">収入</div><div class="money-value">${yen(totalIncome)}</div></div><div class="money-box expense"><div class="money-label">支出</div><div class="money-value">${yen(expense)}</div></div><div class="money-box balance"><div class="money-label">収支</div><div class="money-value">${yen(balance)}</div></div>`;sel.onchange=renderMonthlySummary;}
function renderSummary(){const items=activeSplitItems();const known=items.reduce((s,p)=>s+(Number(p.current)||0),0);const plan=(excel.months||[]).slice(-1)[0]?.payments||[];const latestTotal=plan.reduce((s,p)=>s+(Number(p.amount)||0),0);document.querySelector('#summary').innerHTML=[['分割・リボ残金',known?yen(known):'未入力あり'],['直近月の分割・リボ',yen(latestTotal)],['管理中の項目',`${items.length}件`],['最新データ',excel.source||'—']].map(([l,v])=>`<div class="card"><div class="label">${l}</div><div class="value">${v}</div></div>`).join('');}
function renderSplitItems(){document.querySelector('#splitItems').innerHTML=activeSplitItems().map(p=>{const end=parseEnd(p.end);return `<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.type)}</td><td>${yen(p.monthly)}</td><td>${p.remainingAmount==null?'未入力':yen(p.remainingAmount)}</td><td><input class="input remaining-input" data-key="${esc(p.k)}" type="number" min="0" step="1" value="${p.current==null?'':p.current}" placeholder="残金を入力"></td><td>${end?monthLabel(end):'未設定'}</td></tr>`;}).join('')||'<tr><td colspan="6">表示対象の分割・リボはありません。</td></tr>';document.querySelectorAll('.remaining-input').forEach(el=>el.addEventListener('change',()=>{savedRemaining[el.dataset.key]=Math.max(0,Number(el.value)||0);saveRemaining();render();}));}
function renderSchedules(){const targets=[...(excel.cardSchedules||[]),...(excel.serviceSchedules||[])];document.querySelector('#schedules').innerHTML=targets.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x['引落']||'記載なし')}</td><td>${esc(x['締め日']||'記載なし')}</td><td>${x.source?`<a href="${esc(x.source)}" target="_blank" rel="noopener noreferrer">公式HPを確認</a>`:'—'}</td></tr>`).join('');}
function renderMonthlyPlan(){const months=excel.months||[];const current=new Date().toISOString().slice(0,7);const past=months.filter(m=>m.month<current);const future=months.filter(m=>m.month>=current);const rowHtml=m=>{const payments=m.payments||[];const split=payments.filter(p=>p.type==='分割').reduce((s,p)=>s+(Number(p.amount)||0),0);const ribo=payments.filter(p=>p.type==='リボ').reduce((s,p)=>s+(Number(p.amount)||0),0);return `<tr><td><strong>${monthLabel(m.month)}</strong></td><td>${yen(split)}</td><td>${yen(ribo)}</td><td><strong>${yen(split+ribo)}</strong></td></tr>`;};const button=past.length?`<div class="plan-toggle-row"><button type="button" class="secondary-button" id="togglePastPlan">過去の年月を表示（${past.length}か月）</button></div>`:'';const pastHtml=past.length?`<div id="pastPlan" class="past-plan hidden"><div class="past-plan-label">過去の支払い計画</div><div class="table-wrap"><table><thead><tr><th>月</th><th>分割</th><th>リボ</th><th>合計</th></tr></thead><tbody>${past.map(rowHtml).join('')}</tbody></table></div></div>`:'';document.querySelector('#monthlyPlan').innerHTML=`<tr class="future-plan"><td colspan="4"><div class="table-wrap"><table><thead><tr><th>月</th><th>分割</th><th>リボ</th><th>合計</th></tr></thead><tbody>${future.map(rowHtml).join('')||'<tr><td colspan="4">今後の支払い予定はありません。</td></tr>'}</tbody></table></div></td></tr>`;const planSection=document.querySelector('#monthlyPlan').closest('.panel');let old=planSection.querySelector('.plan-extra');if(old)old.remove();const extra=document.createElement('div');extra.className='plan-extra';extra.innerHTML=button+pastHtml;planSection.appendChild(extra);const toggle=extra.querySelector('#togglePastPlan');if(toggle)toggle.onclick=()=>{const box=extra.querySelector('#pastPlan');const open=box.classList.toggle('hidden');toggle.textContent=open?`過去の年月を表示（${past.length}か月）`:'過去の年月を閉じる';};}
function renderGantt(){const items=activeSplitItems();const ends=items.map(p=>parseEnd(p.end)).filter(Boolean);const current=new Date().toISOString().slice(0,7);const start=current;const end=ends.length?ends.sort().at(-1):addMonths(current,11);const months=monthRange(start,end);const box=document.querySelector('#gantt');if(!box)return;if(!items.length){box.innerHTML='<p class="empty-state">表示対象の分割・リボはありません。</p>';return;}const head=`<div class="gantt-grid gantt-head" style="--gantt-months:${months.length}"><div class="gantt-name">項目</div>${months.map(m=>`<div>${monthLabel(m).replace('年','/').replace('月','')}</div>`).join('')}</div>`;const rows=items.map(p=>{const finish=parseEnd(p.end)||addMonths(current,11);const row=months.map(m=>{const active=m<=finish;return `<div class="gantt-cell ${active?'scheduled':''}">${active?'━':''}</div>`;}).join('');return `<div class="gantt-grid gantt-row" style="--gantt-months:${months.length}"><div class="gantt-name"><strong>${esc(p.name)}</strong><span>${esc(p.type)} / ${yen(p.monthly)}${p.end?` / 完了 ${monthLabel(finish)}`:' / 終了未設定'}</span></div>${row}</div>`;}).join('');box.innerHTML=`<div class="gantt-note">現在月から完了予定月までを1回の支払い＝1か月の線分として表示しています。H/I列に「回/回」等がある月は分割分シート由来の支払予定として扱い、同じ支払いを別計算で足しません。</div><div class="gantt-scroll">${head}${rows}</div>`;}
function renderLife(){const rows=excel.lifeCostMonths||[];const sel=document.querySelector('#lifeMonth');const old=sel.value;sel.innerHTML=rows.map(r=>`<option value="${r.month}">${monthLabel(r.month)}</option>`).join('');sel.value=rows.some(r=>r.month===old)?old:(rows.at(-1)?.month||'');drawPie();sel.onchange=drawPie;}
function drawPie(){const row=(excel.lifeCostMonths||[]).find(r=>r.month===document.querySelector('#lifeMonth').value)||(excel.lifeCostMonths||[]).at(-1);if(!row)return;const entries=[['家賃',row['家賃']],['ガス',row['ガス']],['電気',row['電気']],['携帯',row['携帯']],['水道',row['水道']]].filter(x=>Number(x[1])>0);const total=entries.reduce((s,x)=>s+Number(x[1]),0);const pie=document.querySelector('#pie');pie.style.background=total?`conic-gradient(${entries.map((x,i)=>{const start=entries.slice(0,i).reduce((s,y)=>s+Number(y[1]),0)/total*360;const end=entries.slice(0,i+1).reduce((s,y)=>s+Number(y[1]),0)/total*360;const cls=['#7acb9a','#f3a66b','#76b8e8','#c59de8','#f1cf72'][i];return `${cls} ${start}deg ${end}deg`;}).join(',')})`:'none';document.querySelector('#pieLegend').innerHTML=entries.length?entries.map((x,i)=>`<div><span class="dot" style="background:${['#7acb9a','#f3a66b','#76b8e8','#c59de8','#f1cf72'][i]}"></span>${x[0]}：${yen(x[1])}（${Math.round(Number(x[1])/total*100)}%）</div>`).join(''):'この月の生活費データはありません。';}
const expenseCategories=['食費','日用品','家賃','光熱費','通信費','交通費','医療費','娯楽','その他'];
const incomeCategories=['給与','賞与','その他収入'];
function updateCategoryOptions(){const kind=document.querySelector('#entryKind').value;document.querySelector('#entryCategory').innerHTML=(kind==='収入'?incomeCategories:expenseCategories).map(x=>`<option value="${x}">${x}</option>`).join('');}
function updateConditionalFields(){const method=document.querySelector('#entryMethod').value;const type=document.querySelector('#entryPaymentType').value;document.querySelector('#cardField').classList.toggle('hidden',method!=='クレジットカード');document.querySelector('.card-required').classList.toggle('hidden',method!=='クレジットカード');document.querySelector('#installmentField').classList.toggle('hidden',type!=='分割');document.querySelector('.installment-required').classList.toggle('hidden',type!=='分割');}
function validateEntry(){const errors=[];const date=document.querySelector('#entryDate').value;const kind=document.querySelector('#entryKind').value;const amount=Number(document.querySelector('#entryAmount').value);const method=document.querySelector('#entryMethod').value;const card=document.querySelector('#entryCard').value;const type=document.querySelector('#entryPaymentType').value;if(!date)errors.push('日付を入力してください。');if(!kind)errors.push('収入または支出を選択してください。');if(!document.querySelector('#entryCategory').value)errors.push('カテゴリーを選択してください。');if(!Number.isInteger(amount)||amount<1)errors.push('金額は1円以上の整数で入力してください。');if(method==='クレジットカード'&&!card)errors.push('クレジットカードを選択した場合はカード名が必須です。');if(type==='分割'&&!document.querySelector('#entryInstallments').value)errors.push('分割回数を選択してください。');if(kind==='収入'&&type!=='通常')errors.push('収入は支払区分を「通常」にしてください。');return errors;}
function renderManualEntries(){const box=document.querySelector('#manualEntries');if(!manualEntries.length){box.innerHTML='';return;}box.innerHTML=`<h3>このブラウザで登録した入力</h3><div class="entry-list">${manualEntries.slice().reverse().map(e=>`<div class="entry-row"><span>${esc(e.date)}</span><span>${esc(e.kind)}</span><span>${esc(e.category)}${e.card?` / ${esc(e.card)}`:''}${e.type!=='通常'?` / ${esc(e.type)}${e.installments?` ${esc(e.installments)}回`:''}`:''}</span><strong>${yen(e.amount)}</strong><span class="entry-memo">${esc(e.memo||'')}</span><button class="delete-entry" data-id="${esc(e.id)}" title="削除">×</button></div>`).join('')}</div>`;box.querySelectorAll('.delete-entry').forEach(b=>b.onclick=()=>{manualEntries=manualEntries.filter(e=>e.id!==b.dataset.id);saveEntries();renderManualEntries();renderMonthlySummary();});}
function initEntryForm(){const form=document.querySelector('#entryForm');document.querySelector('#entryDate').value=new Date().toISOString().slice(0,10);document.querySelector('#entryKind').onchange=()=>{updateCategoryOptions();updateConditionalFields();};document.querySelector('#entryMethod').onchange=updateConditionalFields;document.querySelector('#entryPaymentType').onchange=updateConditionalFields;updateCategoryOptions();updateConditionalFields();form.onsubmit=e=>{e.preventDefault();const errors=validateEntry();const err=document.querySelector('#inputError');const msg=document.querySelector('#inputMessage');if(errors.length){err.textContent=errors.join(' ');msg.textContent='';return;}err.textContent='';const entry={id:`${Date.now()}-${Math.random().toString(36).slice(2)}`,date:document.querySelector('#entryDate').value,kind:document.querySelector('#entryKind').value,category:document.querySelector('#entryCategory').value,amount:Number(document.querySelector('#entryAmount').value),method:document.querySelector('#entryMethod').value,card:document.querySelector('#entryCard').value,type:document.querySelector('#entryPaymentType').value,installments:document.querySelector('#entryPaymentType').value==='分割'?document.querySelector('#entryInstallments').value:'',memo:document.querySelector('#entryMemo').value.trim()};manualEntries.push(entry);saveEntries();form.reset();document.querySelector('#entryDate').value=new Date().toISOString().slice(0,10);updateCategoryOptions();updateConditionalFields();msg.textContent='登録しました。月次収支にも反映されます。';renderManualEntries();renderMonthlySummary();};renderManualEntries();}
function render(){if(!excel)return;renderMonthlySummary();renderSummary();renderSplitItems();renderSchedules();renderMonthlyPlan();renderGantt();renderLife();initEntryForm();document.querySelector('#dataStatus').textContent=`Excelデータ読み込み済み：${excel.source}（${(excel.months||[]).length}か月）`;}
async function loadExcel(){try{const r=await fetch(EXCEL_URL,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);excel=await r.json();render();}catch(e){console.error(e);document.querySelector('#dataStatus').textContent='Excelデータの読み込みに失敗しました。';}}
loadExcel();
