const KEY='budget-demo-v2';
const EXCEL_URL='data/budget-data.json';
const sample={income:300000,months:['2026-09','2026-10','2026-11','2026-12','2027-01','2027-02'],utilities:{'2026-09':30000,'2026-10':28000,'2026-11':27000,'2026-12':32000,'2027-01':30000,'2027-02':29000},fixed:{'2026-09':100000,'2026-10':100000,'2026-11':100000,'2026-12':100000,'2027-01':100000,'2027-02':100000},other:{'2026-09':50000,'2026-10':48000,'2026-11':45000,'2026-12':45000,'2027-01':45000,'2027-02':45000},payments:[{id:1,name:'リボA',type:'リボ',month:'2026-09',monthly:10000,balance:50000,count:5,paid:0},{id:2,name:'分割B',type:'分割',month:'2026-09',monthly:15000,balance:45000,count:3,paid:0},{id:3,name:'通信費',type:'固定費',month:'2026-09',monthly:12000,balance:72000,count:6,paid:0}]};
let data=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(sample));
let excel=null;
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n||0);
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function months(){return data.months}
function monthlyPayment(p,m){const start=new Date(p.month+'-01'),cur=new Date(m+'-01');if(cur<start||p.balance-p.paid<=0)return 0;const diff=(cur.getFullYear()-start.getFullYear())*12+cur.getMonth()-start.getMonth();return diff>=p.count?0:Math.min(p.monthly,Math.max(0,p.balance-p.paid-diff*p.monthly))}
function renderExcel(){const status=document.querySelector('#dataStatus'),box=document.querySelector('#excelSummary');if(!excel){status.textContent='Excelデータを読み込めませんでした。サンプルデータを表示しています。';box.innerHTML='<p>data/budget-data.json を確認してください。</p>';return}status.textContent=`Excelデータ読み込み済み：${excel.source}（${excel.sheetNames.length}シート）`;const chips=Object.entries(excel.categories).map(([k,v])=>`<div class="card"><div class="label">${k}</div><div class="value">${v.length}シート</div><small>${v.length?v.join(' / '):'検出なし'}</small></div>`).join('');box.innerHTML=`<p><strong>生成日時：</strong>${excel.generatedAt}</p><div class="cards">${chips}</div><details><summary>読み込んだシート一覧</summary><ul>${excel.sheetNames.map(s=>`<li>${s}</li>`).join('')}</ul></details>`}
function render(){const active=data.payments.filter(p=>p.balance-p.paid>0);const remaining=active.reduce((s,p)=>s+Math.max(0,p.balance-p.paid),0);const next=months().map(m=>({m,total:(data.fixed[m]||0)+(data.utilities[m]||0)+(data.other[m]||0)+data.payments.reduce((s,p)=>s+monthlyPayment(p,m),0)}));const max=next.reduce((a,b)=>Math.max(a,b.total),0);document.querySelector('#summary').innerHTML=[['今後の支払残高',yen(remaining)],['直近月の必要額',yen(next[0]?.total)],['月間最高必要額',yen(max)],['支払い中の件数',active.length+'件']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('');
document.querySelector('#payments').innerHTML=data.payments.map(p=>{const rem=Math.max(0,p.balance-p.paid),count=Math.max(0,Math.ceil(rem/Math.max(1,p.monthly))),done=rem<=0;return `<tr><td><strong>${p.name}</strong></td><td>${p.type}</td><td>${p.month}</td><td>${yen(p.monthly)}</td><td>${yen(rem)}</td><td>${count}回</td><td><input class="input paid-input" data-id="${p.id}" type="number" min="0" step="100" value="${p.paid}"></td><td><span class="status ${done?'paid':'active'}">${done?'完済':'支払中'}</span></td><td><button class="secondary del" data-id="${p.id}">削除</button></td></tr>`}).join('');
document.querySelector('#months').innerHTML=months().map(m=>{const installments=data.payments.reduce((s,p)=>s+monthlyPayment(p,m),0),total=(data.fixed[m]||0)+(data.utilities[m]||0)+(data.other[m]||0)+installments,remain=data.income-total;return `<tr><td><strong>${m.slice(0,7).replace('-','年')}月</strong></td><td>${yen(data.income)}</td><td>${yen(data.fixed[m])}</td><td>${yen(data.utilities[m])}</td><td>${yen(installments)}</td><td>${yen(data.other[m])}</td><td><strong>${yen(total)}</strong></td><td class="${remain>=0?'positive':'negative'}">${yen(remain)}</td></tr>`}).join('');
document.querySelector('#milestones').innerHTML=data.payments.map(p=>{const rem=Math.max(0,p.balance-p.paid);if(!rem)return `<div class="milestone"><strong>${p.name}</strong>：完済済み</div>`;const end=new Date(p.month+'-01');end.setMonth(end.getMonth()+Math.ceil(rem/p.monthly)-1);return `<div class="milestone"><strong>${p.name}</strong>：あと${Math.ceil(rem/p.monthly)}回・${yen(rem)} → ${end.getFullYear()}年${end.getMonth()+1}月ごろ完済</div>`}).join('');
document.querySelectorAll('.paid-input').forEach(el=>el.onchange=()=>{const p=data.payments.find(x=>x.id==el.dataset.id);p.paid=Math.min(p.balance,Math.max(0,Number(el.value)));save()});document.querySelectorAll('.del').forEach(el=>el.onclick=()=>{data.payments=data.payments.filter(p=>p.id!=el.dataset.id);save()});renderExcel()}
document.querySelector('#addPayment').onclick=()=>document.querySelector('#paymentDialog').showModal();
document.querySelector('#paymentForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.payments.push({id:Date.now(),name:f.get('name'),type:f.get('type'),month:f.get('month'),monthly:Number(f.get('monthly')),balance:Number(f.get('balance')),count:Number(f.get('count')),paid:0});e.target.reset();document.querySelector('#paymentDialog').close();save()};
document.querySelector('#resetBtn').onclick=()=>{data=JSON.parse(JSON.stringify(sample));save()};
async function loadExcel(){try{const r=await fetch(EXCEL_URL,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);excel=await r.json();}catch(e){console.error(e)}render()}
loadExcel();
